28/01/13
First commit following testing on device. Following issues fixed:

 - NoSuchMethodError thrown when using Notification.Builder.
  - Fix required downloading Android Support Libraries
  - Referenced NotificationCompat instead of Notification
  
 - Multiple foreground services launched when closing/opening application and re-logging in.
  - App now checks for shared preferences when opening the SentinelLogin activity and automatically forwards to Sentinel activity.
  
 - Multiple application icons resolved by removing android.intent.category.MAIN from manifiest file
 
 - Application now correctly clears shared preferences when logging out